name: Deploy SDK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Set token
        run: npm config set //registry.npmjs.org/:_authToken="${{secrets.NPM_AUTH_TOKEN}}"

      - name: Install dependencies
        run: npm install

      - name: Install specific typescript version
        run: npm install typescript@4.7.4 -g

      - name: Build SDK
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Publish to npm
        run: npm publish
